const directory = [
  {
    id: "drive-c",
    name: "C:",
    type: "drive",
    children: [
      {
        id: "folder-program-files",
        name: "Program Files",
        type: "folder",
        children: [
          { id: "app-about", type: "app", appId: "about" },
          { id: "app-tipOfTheDay", type: "app", appId: "tipOfTheDay" },
          { id: "app-pdfviewer", type: "app", appId: "pdfviewer" },
          { id: "app-notepad", type: "app", appId: "notepad" },
          { id: "app-image-viewer", type: "app", appId: "image-viewer" },
          { id: "app-clippy", type: "app", appId: "clippy" },
          { id: "app-webamp", type: "app", appId: "webamp" },
          { id: "app-appmaker", type: "app", appId: "appmaker" },
          { id: "app-alertTest", type: "app", appId: "alertTest" },
          { id: "app-themetocss", type: "app", appId: "themetocss" },
          {
            id: "app-soundschemeexplorer",
            type: "app",
            appId: "soundschemeexplorer",
          },
          { id: "app-explorer", type: "app", appId: "explorer" },
          { id: "app-my-computer", type: "app", appId: "my-computer" },
          { id: "app-my-documents", type: "app", appId: "my-documents" },
          { id: "app-recycle-bin", type: "app", appId: "recycle-bin" },
          {
            id: "app-internet-explorer",
            type: "app",
            appId: "internet-explorer",
          },
          { id: "app-pinball", type: "app", appId: "pinball" },
          { id: "app-paint", type: "app", appId: "paint" },
          {
            id: "app-display-properties",
            type: "app",
            appId: "display-properties",
          },
          {
            id: "app-network-neighborhood",
            type: "app",
            appId: "network-neighborhood",
          },
        ],
      },
      {
        id: "folder-user",
        name: "user",
        type: "folder",
        children: [
          {
            id: "folder-desktop",
            name: "desktop",
            type: "folder",
            children: [
              {
                id: "shortcut-to-my-computer",
                type: "shortcut",
                targetId: "app-my-computer",
                name: "My Computer",
              },
              {
                id: "shortcut-to-my-documents",
                type: "shortcut",
                targetId: "app-my-documents",
                name: "My Documents",
              },
              {
                id: "shortcut-to-recycle-bin",
                type: "shortcut",
                targetId: "app-recycle-bin",
                name: "Recycle Bin",
              },
              {
                id: "shortcut-to-network-neighborhood",
                type: "shortcut",
                targetId: "app-network-neighborhood",
                name: "Network Neighborhood",
              },
              {
                id: "shortcut-to-tipOfTheDay",
                type: "shortcut",
                targetId: "app-tipOfTheDay",
                name: "Tip of the Day",
              },
              {
                id: "shortcut-to-notepad",
                type: "shortcut",
                targetId: "app-notepad",
                name: "Notepad",
              },
              {
                id: "shortcut-to-image-viewer",
                type: "shortcut",
                targetId: "app-image-viewer",
                name: "Image Viewer",
              },
              {
                id: "shortcut-to-clippy",
                type: "shortcut",
                targetId: "app-clippy",
                name: "Assistant",
              },
              {
                id: "shortcut-to-webamp",
                type: "shortcut",
                targetId: "app-webamp",
                name: "Winamp",
              },
              {
                id: "shortcut-to-appmaker",
                type: "shortcut",
                targetId: "app-appmaker",
                name: "App Maker",
              },
              {
                id: "shortcut-to-alertTest",
                type: "shortcut",
                targetId: "app-alertTest",
                name: "Alert Test",
              },
              {
                id: "shortcut-to-internet-explorer",
                type: "shortcut",
                targetId: "app-internet-explorer",
                name: "Internet Explorer",
              },
              {
                id: "shortcut-to-pinball",
                type: "shortcut",
                targetId: "app-pinball",
                name: "3D Pinball",
              },
              {
                id: "shortcut-to-paint",
                type: "shortcut",
                targetId: "app-paint",
                name: "Paint",
              },
              {
                id: "file-resume",
                type: "file",
                name: "Resume.pdf",
                contentUrl: "public/files/Resume.pdf",
              },
              {
                id: "file-readme",
                type: "file",
                name: "README.md",
                contentUrl: "files/README.md",
              },
            ],
          },
          {
            id: "folder-documents",
            name: "Documents",
            type: "folder",
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "drive-d",
    name: "D:",
    type: "drive",
    children: [],
  },
];

export default directory;
