export const ICONS = {
  about: new URL("../assets/icons/COMCTL32_20481.ico", import.meta.url).href,
  pdf: new URL("../assets/icons/word_001.ico", import.meta.url).href,
  tip: new URL("../assets/icons/help_book_cool-0.png", import.meta.url).href,
  notepad: new URL("../assets/icons/NOTEPAD_1.ico", import.meta.url).href,
  clippy: new URL("../assets/icons/msagent_file-1.png", import.meta.url).href,
  webamp: new URL("../assets/icons/winamp.png", import.meta.url).href,
  computer: new URL("../assets/icons/computer_explorer.ico", import.meta.url).href,
  folder: new URL("../assets/icons/directory_open_file_mydocs-1.png", import.meta.url).href,
  warning: new URL("../assets/icons/msg_warning-0.png", import.meta.url).href,
  shutdown: new URL("../assets/icons/shut_down_normal-0.png", import.meta.url).href,
  windows: new URL("../assets/icons/windows-4.png", import.meta.url).href,
  key: new URL("../assets/icons/key_win-4.png", import.meta.url).href,
  key_alt: new URL("../assets/icons/key_win_alt.ico", import.meta.url).href,
  shell: new URL("../assets/icons/SHELL32_3.ico", import.meta.url).href,
  systray: new URL("../assets/icons/SYSTRAY_220.ico", import.meta.url).href,
  rnaui: new URL("../assets/icons/RNAUI_106.ico", import.meta.url).href,
  setdebug: new URL("../assets/icons/SETDEBUG_100.ico", import.meta.url).href,
  mmsys: new URL("../assets/icons/MMSYS_110.ico", import.meta.url).href,
  comctl32: new URL("../assets/icons/COMCTL32_20481.ico", import.meta.url).href,
  desktop_old: new URL("../assets/icons/desktop_old-4.png", import.meta.url).href,
  folder_small: new URL("../assets/icons/directory_open_file_mydocs_small-5.png", import.meta.url).href,
};