export const languages = [
    {
        id: 'text',
        name: 'Plain Text',
        extensions: ['txt'],
        hljs: 'text',
        prettier: null,
    },
    {
        id: 'javascript',
        name: 'JavaScript',
        extensions: ['js'],
        hljs: 'javascript',
        prettier: 'babel',
    },
    {
        id: 'html',
        name: 'HTML',
        extensions: ['html', 'htm'],
        hljs: 'html',
        prettier: 'html',
    },
    {
        id: 'css',
        name: 'CSS',
        extensions: ['css'],
        hljs: 'css',
        prettier: 'css',
    },
    {
        id: 'json',
        name: 'JSON',
        extensions: ['json'],
        hljs: 'json',
        prettier: 'json',
    },
    {
        id: 'python',
        name: 'Python',
        extensions: ['py'],
        hljs: 'python',
        prettier: null,
    },
    {
        id: 'java',
        name: 'Java',
        extensions: ['java'],
        hljs: 'java',
        prettier: null,
    },
    {
        id: 'c',
        name: 'C',
        extensions: ['c', 'h'],
        hljs: 'c',
        prettier: null,
    },
    {
        id: 'cpp',
        name: 'C++',
        extensions: ['cpp', 'hpp'],
        hljs: 'cpp',
        prettier: null,
    },
    {
        id: 'csharp',
        name: 'C#',
        extensions: ['cs'],
        hljs: 'csharp',
        prettier: null,
    },
    {
        id: 'sql',
        name: 'SQL',
        extensions: ['sql'],
        hljs: 'sql',
        prettier: null,
    },
    {
        id: 'php',
        name: 'PHP',
        extensions: ['php'],
        hljs: 'php',
        prettier: null,
    },
    {
        id: 'ruby',
        name: 'Ruby',
        extensions: ['rb'],
        hljs: 'ruby',
        prettier: null,
    },
    {
        id: 'go',
        name: 'Go',
        extensions: ['go'],
        hljs: 'go',
        prettier: null,
    },
    {
        id: 'rust',
        name: 'Rust',
        extensions: ['rs'],
        hljs: 'rust',
        prettier: null,
    },
    {
        id: 'typescript',
        name: 'TypeScript',
        extensions: ['ts'],
        hljs: 'typescript',
        prettier: 'babel',
    },
    {
        id: 'bash',
        name: 'Bash',
        extensions: ['sh'],
        hljs: 'bash',
        prettier: null,
    },
    {
        id: 'markdown',
        name: 'Markdown',
        extensions: ['md', 'mdc', 'markdown'],
        hljs: 'markdown',
        prettier: null,
    },
];