export const soundSchemes = {
  Default: {
    Default: 'ding.wav',
    AppGPFault: '',
    Maximize: '',
    MenuCommand: '',
    MenuPopup: '',
    Minimize: '',
    RestoreDown: '',
    RestoreUp: '',
    SystemAsterisk: 'chord.wav',
    SystemExclamation: 'chord.wav',
    SystemExit: 'tada.wav',
    SystemHand: 'chord.wav',
    SystemQuestion: 'chord.wav',
    WindowsLogon: 'the microsoft sound.wav',
    EmptyRecycleBin: 'ding.wav',
    ChangeTheme: '',
    DeviceConnect: '',
    DeviceDisconnect: '',
    DeviceFail: '',
    LowBatteryAlarm: 'ding.wav',
    MailBeep: 'chimes.wav',
    SystemNotification: '',
    WindowsLogoff: '',
    StartNavigation: 'start.wav',
  },
};
