export const soundSchemes = {
  Default: {
    Default: 'ding.wav',
    AppGPFault: '',
    Maximize: '',
    MenuCommand: '',
    MenuPopup: '',
    Minimize: '',
    RestoreDown: '',
    RestoreUp: '',
    SystemAsterisk: 'chord.wav',
    SystemExclamation: 'chord.wav',
    SystemExit: 'tada.wav',
    SystemHand: 'chord.wav',
    SystemQuestion: 'chord.wav',
    WindowsLogon: 'the microsoft sound.wav',
    EmptyRecycleBin: 'ding.wav',
    ChangeTheme: '',
    DeviceConnect: '',
    DeviceDisconnect: '',
    DeviceFail: '',
    LowBatteryAlarm: 'ding.wav',
    MailBeep: 'chimes.wav',
    SystemNotification: '',
    WindowsLogoff: '',
    StartNavigation: 'start.wav',
  },
  '60s USA': {
    Default: "the 60's usa beep.wav",
    AppGPFault: "the 60's usa program error.wav",
    Maximize: "the 60's usa maximize.wav",
    MenuCommand: "the 60's usa menu command.wav",
    MenuPopup: "the 60's usa menu popup.wav",
    Minimize: "the 60's usa minimize.wav",
    RestoreDown: "the 60's usa restore down.wav",
    RestoreUp: "the 60's usa restore up.wav",
    SystemAsterisk: "the 60's usa asterisk.wav",
    SystemExclamation: "the 60's usa exclamation.wav",
    SystemExit: "the 60's usa exit windows.wav",
    SystemHand: "the 60's usa critical stop.wav",
    SystemQuestion: "the 60's usa question.wav",
    WindowsLogon: "the 60's usa startup.wav",
    EmptyRecycleBin: "the 60's usa empty recycle bin.wav",
    ChangeTheme: '',
    DeviceConnect: '',
    DeviceDisconnect: '',
    DeviceFail: '',
    LowBatteryAlarm: '',
    MailBeep: '',
    SystemNotification: '',
    WindowsLogoff: '',
  },
  'Dangerous Creatures': {
    Default: 'Dangerous Creatures default sound.wav',
    AppGPFault: 'Dangerous Creatures program error.wav',
    Maximize: 'Dangerous Creatures maximize.wav',
    MenuCommand: 'Dangerous Creatures menu command.wav',
    MenuPopup: 'Dangerous Creatures menu popup.wav',
    Minimize: 'Dangerous Creatures minimize.wav',
    Open: '',
    Close: '',
    RestoreDown: 'Dangerous Creatures minimize.wav',
    RestoreUp: 'Dangerous Creatures maximize.wav',
    RingIn: '',
    Ringout: '',
    SystemAsterisk: 'Dangerous Creatures asterisk.wav',
    SystemDefault: 'Dangerous Creatures beep.wav',
    SystemExclamation: 'Dangerous Creatures exclamation.wav',
    SystemExit: 'Dangerous Creatures startup.wav',
    SystemHand: 'Dangerous Creatures critical stop.wav',
    SystemQuestion: 'Dangerous Creatures question.wav',
    WindowsLogon: 'Dangerous Creatures startup.wav',
    EmptyRecycleBin: 'Dangerous Creatures empty recycle bin.wav',
    ChangeTheme: '',
    DeviceConnect: '',
    DeviceDisconnect: '',
    DeviceFail: '',
    LowBatteryAlarm: '',
    MailBeep: '',
    SystemNotification: '',
    WindowsLogoff: '',
    StartNavigation: '',
  },
  'Inside Your Computer': {
    Default: 'Inside your Computer default sound.wav',
    AppGPFault: 'Inside your Computer program error.wav',
    Maximize: 'Inside your Computer maximize.wav',
    MenuCommand: 'Inside your Computer menu command.wav',
    MenuPopup: 'Inside your Computer menu popup.wav',
    Minimize: 'Inside your Computer minimize.wav',
    RestoreDown: 'Inside your Computer restore down.wav',
    RestoreUp: 'Inside your Computer restore up.wav',
    SystemAsterisk: 'Inside your Computer asterisk.wav',
    SystemExclamation: 'Inside your Computer exclamation.wav',
    SystemExit: 'Inside your Computer startup.wav',
    SystemHand: 'Inside your Computer critical stop.wav',
    SystemQuestion: 'Inside your Computer question.wav',
    WindowsLogon: 'Inside your Computer startup.wav',
    EmptyRecycleBin: 'Inside your Computer empty recycle bin.wav',
  }
};
