export default {
  'chimes': new URL('../assets/audio/CHIMES.WAV', import.meta.url).href,
  'chord': new URL('../assets/audio/CHORD.WAV', import.meta.url).href,
  'ding': new URL('../assets/audio/DING.WAV', import.meta.url).href,
  'logoff': new URL('../assets/audio/LOGOFF.WAV', import.meta.url).href,
  'notify': new URL('../assets/audio/NOTIFY.WAV', import.meta.url).href,
  'recycle': new URL('../assets/audio/RECYCLE.WAV', import.meta.url).href,
  'start': new URL('../assets/audio/START.WAV', import.meta.url).href,
  'tada': new URL('../assets/audio/TADA.WAV', import.meta.url).href,
  'the_microsoft_sound': new URL('../assets/audio/The Microsoft Sound.wav', import.meta.url).href,
  "the_60's_usa_asterisk": new URL("../assets/audio/the 60's usa asterisk.wav", import.meta.url).href,
  "the_60's_usa_beep": new URL("../assets/audio/the 60's usa beep.wav", import.meta.url).href,
  "the_60's_usa_critical_stop": new URL("../assets/audio/the 60's usa critical stop.wav", import.meta.url).href,
  "the_60's_usa_empty_recycle_bin": new URL("../assets/audio/the 60's usa empty recycle bin.wav", import.meta.url).href,
  "the_60's_usa_exclamation": new URL("../assets/audio/the 60's usa exclamation.wav", import.meta.url).href,
  "the_60's_usa_exit_windows": new URL("../assets/audio/the 60's usa exit windows.wav", import.meta.url).href,
  "the_60's_usa_maximize": new URL("../assets/audio/the 60's usa maximize.wav", import.meta.url).href,
  "the_60's_usa_menu_command": new URL("../assets/audio/the 60's usa menu command.wav", import.meta.url).href,
  "the_60's_usa_menu_popup": new URL("../assets/audio/the 60's usa menu popup.wav", import.meta.url).href,
  "the_60's_usa_minimize": new URL("../assets/audio/the 60's usa minimize.wav", import.meta.url).href,
  "the_60's_usa_program_error": new URL("../assets/audio/the 60's usa program error.wav", import.meta.url).href,
  "the_60's_usa_question": new URL("../assets/audio/the 60's usa question.wav", import.meta.url).href,
  "the_60's_usa_restore_down": new URL("../assets/audio/the 60's usa restore down.wav", import.meta.url).href,
  "the_60's_usa_restore_up": new URL("../assets/audio/the 60's usa restore up.wav", import.meta.url).href,
  "the_60's_usa_startup": new URL("../assets/audio/the 60's usa startup.wav", import.meta.url).href,
};