export const soundSchemes = {
  Default: {
    Default: 'ding.wav',
    AppGPFault: '',
    Maximize: '',
    MenuCommand: '',
    MenuPopup: '',
    Minimize: '',
    RestoreDown: '',
    RestoreUp: '',
    SystemAsterisk: 'chord.wav',
    SystemExclamation: 'chord.wav',
    SystemExit: 'tada.wav',
    SystemHand: 'chord.wav',
    SystemQuestion: 'chord.wav',
    WindowsLogon: 'the microsoft sound.wav',
    EmptyRecycleBin: 'ding.wav',
    ChangeTheme: '',
    DeviceConnect: '',
    DeviceDisconnect: '',
    DeviceFail: '',
    LowBatteryAlarm: 'ding.wav',
    MailBeep: 'chimes.wav',
    SystemNotification: '',
    WindowsLogoff: '',
    StartNavigation: 'start.wav',
  },
  '60s USA': {
    Default: "the 60's usa beep.wav",
    AppGPFault: "the 60's usa program error.wav",
    Maximize: "the 60's usa maximize.wav",
    MenuCommand: "the 60's usa menu command.wav",
    MenuPopup: "the 60's usa menu popup.wav",
    Minimize: "the 60's usa minimize.wav",
    RestoreDown: "the 60's usa restore down.wav",
    RestoreUp: "the 60's usa restore up.wav",
    SystemAsterisk: "the 60's usa asterisk.wav",
    SystemExclamation: "the 60's usa exclamation.wav",
    SystemExit: "the 60's usa exit windows.wav",
    SystemHand: "the 60's usa critical stop.wav",
    SystemQuestion: "the 60's usa question.wav",
    WindowsLogon: "the 60's usa startup.wav",
    EmptyRecycleBin: "the 60's usa empty recycle bin.wav",
    ChangeTheme: '',
    DeviceConnect: '',
    DeviceDisconnect: '',
    DeviceFail: '',
    LowBatteryAlarm: '',
    MailBeep: '',
    SystemNotification: '',
    WindowsLogoff: '',
  },
};
