export default {
  'chimes': new URL('../assets/audio/CHIMES.WAV', import.meta.url).href,
  'chord': new URL('../assets/audio/CHORD.WAV', import.meta.url).href,
  'ding': new URL('../assets/audio/DING.WAV', import.meta.url).href,
  'logoff': new URL('../assets/audio/LOGOFF.WAV', import.meta.url).href,
  'notify': new URL('../assets/audio/NOTIFY.WAV', import.meta.url).href,
  'recycle': new URL('../assets/audio/RECYCLE.WAV', import.meta.url).href,
  'start': new URL('../assets/audio/START.WAV', import.meta.url).href,
  'tada': new URL('../assets/audio/TADA.WAV', import.meta.url).href,
  'the_microsoft_sound': new URL('../assets/audio/The Microsoft Sound.wav', import.meta.url).href,
  
  "the_60's_usa_asterisk": new URL("../assets/audio/the 60's usa asterisk.wav", import.meta.url).href,
  "the_60's_usa_beep": new URL("../assets/audio/the 60's usa beep.wav", import.meta.url).href,
  "the_60's_usa_critical_stop": new URL("../assets/audio/the 60's usa critical stop.wav", import.meta.url).href,
  "the_60's_usa_empty_recycle_bin": new URL("../assets/audio/the 60's usa empty recycle bin.wav", import.meta.url).href,
  "the_60's_usa_exclamation": new URL("../assets/audio/the 60's usa exclamation.wav", import.meta.url).href,
  "the_60's_usa_exit_windows": new URL("../assets/audio/the 60's usa exit windows.wav", import.meta.url).href,
  "the_60's_usa_maximize": new URL("../assets/audio/the 60's usa maximize.wav", import.meta.url).href,
  "the_60's_usa_menu_command": new URL("../assets/audio/the 60's usa menu command.wav", import.meta.url).href,
  "the_60's_usa_menu_popup": new URL("../assets/audio/the 60's usa menu popup.wav", import.meta.url).href,
  "the_60's_usa_minimize": new URL("../assets/audio/the 60's usa minimize.wav", import.meta.url).href,
  "the_60's_usa_program_error": new URL("../assets/audio/the 60's usa program error.wav", import.meta.url).href,
  "the_60's_usa_question": new URL("../assets/audio/the 60's usa question.wav", import.meta.url).href,
  "the_60's_usa_restore_down": new URL("../assets/audio/the 60's usa restore down.wav", import.meta.url).href,
  "the_60's_usa_restore_up": new URL("../assets/audio/the 60's usa restore up.wav", import.meta.url).href,
  "the_60's_usa_startup": new URL("../assets/audio/the 60's usa startup.wav", import.meta.url).href,

  'dangerous_creatures_asterisk': new URL('../assets/audio/Dangerous Creatures asterisk.wav', import.meta.url).href,
  'dangerous_creatures_beep': new URL('../assets/audio/Dangerous Creatures beep.wav', import.meta.url).href,
  'dangerous_creatures_critical_stop': new URL('../assets/audio/Dangerous Creatures critical stop.wav', import.meta.url).href,
  'dangerous_creatures_default_sound': new URL('../assets/audio/Dangerous Creatures default sound.wav', import.meta.url).href,
  'dangerous_creatures_empty_recycle_bin': new URL('../assets/audio/Dangerous Creatures empty recycle bin.wav', import.meta.url).href,
  'dangerous_creatures_exclamation': new URL('../assets/audio/Dangerous Creatures exclamation.wav', import.meta.url).href,
  'dangerous_creatures_maximize': new URL('../assets/audio/Dangerous Creatures maximize.wav', import.meta.url).href,
  'dangerous_creatures_menu_command': new URL('../assets/audio/Dangerous Creatures menu command.wav', import.meta.url).href,
  'dangerous_creatures_menu_popup': new URL('../assets/audio/Dangerous Creatures menu popup.wav', import.meta.url).href,
  'dangerous_creatures_minimize': new URL('../assets/audio/Dangerous Creatures minimize.wav', import.meta.url).href,
  'dangerous_creatures_program_error': new URL('../assets/audio/Dangerous Creatures program error.wav', import.meta.url).href,
  'dangerous_creatures_question': new URL('../assets/audio/Dangerous Creatures question.wav', import.meta.url).href,
  'dangerous_creatures_startup': new URL('../assets/audio/Dangerous Creatures startup.wav', import.meta.url).href,
  
  'inside_your_computer_asterisk': new URL('../assets/audio/Inside your Computer asterisk.wav', import.meta.url).href,
  'inside_your_computer_beep': new URL('../assets/audio/Inside your Computer beep.wav', import.meta.url).href,
  'inside_your_computer_critical_stop': new URL('../assets/audio/Inside your Computer critical stop.wav', import.meta.url).href,
  'inside_your_computer_default_sound': new URL('../assets/audio/Inside your Computer default sound.wav', import.meta.url).href,
  "inside_your_computer_empty_recycle_bin": new URL("../assets/audio/Inside your Computer empty recycle bin.wav", import.meta.url).href,
  "inside_your_computer_exclamation": new URL("../assets/audio/Inside your Computer exclamation.wav", import.meta.url).href,
  "inside_your_computer_exit_windows": new URL("../assets/audio/Inside your Computer exit windows.wav", import.meta.url).href,
  "inside_your_computer_maximize": new URL("../assets/audio/Inside your Computer maximize.wav", import.meta.url).href,
  "inside_your_computer_menu_command": new URL("../assets/audio/Inside your Computer menu command.wav", import.meta.url).href,
  "inside_your_computer_menu_popup": new URL("../assets/audio/Inside your Computer menu popup.wav", import.meta.url).href,
  "inside_your_computer_minimize": new URL("../assets/audio/Inside your Computer minimize.wav", import.meta.url).href,
  "inside_your_computer_program_error": new URL("../assets/audio/Inside your Computer program error.wav", import.meta.url).href,
  "inside_your_computer_question": new URL("../assets/audio/Inside your Computer question.wav", import.meta.url).href,
  "inside_your_computer_restore_down": new URL("../assets/audio/Inside your Computer restore down.wav", import.meta.url).href,
  "inside_your_computer_restore_up": new URL("../assets/audio/Inside your Computer restore up.wav", import.meta.url).href,
  "inside_your_computer_startup": new URL("../assets/audio/Inside your Computer startup.wav", import.meta.url).href,
};