import { wallpapers } from "./wallpapers.js";

export const themes = {
  default: {
    id: "default",
    name: "Windows Default",
    stylesheet: "windows-default.css",
    wallpaper: null,
    soundScheme: "Default",
    iconScheme: "default",
  },
  "peggys-pastels": {
    id: "peggys-pastels",
    name: "Peggy's Pastels",
    stylesheet: "peggys-pastels.css",
    wallpaper: null,
    soundScheme: "Default",
    iconScheme: "default",
  },
  blue: {
    id: "blue",
    name: "Blue",
    stylesheet: "blue.css",
    wallpaper: null,
    soundScheme: "Default",
    iconScheme: "default",
  },
  "60s-usa": {
    id: "60s-usa",
    name: "60s USA",
    stylesheet: "60s-usa.css",
    wallpaper: wallpapers.themes.find((w) => w.id === "the60sUSA").src,
    soundScheme: "60s USA",
    iconScheme: "60s-usa",
  },
  "dangerous-creatures": {
    id: "dangerous-creatures",
    name: "Dangerous Creatures",
    stylesheet: "dangerous-creatures.css",
    wallpaper: wallpapers.themes.find((w) => w.id === "dangerousCreatures").src,
    soundScheme: "Dangerous Creatures",
    iconScheme: "dangerous-creatures",
  },
  baseball: {
    id: "baseball",
    name: "Baseball",
    stylesheet: "baseball.css",
    wallpaper: wallpapers.themes.find((w) => w.id === "baseball").src,
    soundScheme: "Baseball",
    iconScheme: "baseball",
  },
  jungle: {
    id: "jungle",
    name: "Jungle",
    stylesheet: "jungle.css",
    wallpaper: wallpapers.themes.find((w) => w.id === "jungle").src,
    soundScheme: "Jungle",
    iconScheme: "jungle",
  },
  space: {
    id: "space",
    name: "Space",
    stylesheet: "space.css",
    wallpaper: wallpapers.themes.find((w) => w.id === "space").src,
    soundScheme: "Space",
    iconScheme: "space",
    screensaver: "space",
  },
  underwater: {
    id: "underwater",
    name: "Underwater",
    stylesheet: "underwater.css",
    wallpaper: wallpapers.themes.find((w) => w.id === "underwater").src,
    soundScheme: "Underwater",
    iconScheme: "underwater",
    screensaver: "underwater",
  },
  //'memphis-milano': {
  //  id: 'memphis-milano',
  //  name: 'Memphis Milano',
  //  stylesheet: 'memphis-milano.css',
  //  wallpaper: null,
  //  soundScheme: 'Default',
  //},
  "inside-your-computer": {
    id: "inside-your-computer",
    name: "Inside Your Computer",
    stylesheet: "inside-your-computer.css",
    wallpaper: wallpapers.themes.find((w) => w.id === "insideYourComputer").src,
    soundScheme: "Inside Your Computer",
    iconScheme: "inside-your-computer",
  },
  sports: {
    id: "sports",
    name: "Sports",
    stylesheet: "sports.css",
    wallpaper: wallpapers.themes.find((w) => w.id === "sports").src,
    soundScheme: "Sports",
    iconScheme: "sports",
  },
  "leonardo-da-vinci": {
    id: "leonardo-da-vinci",
    name: "Leonardo da Vinci",
    stylesheet: "leonardo-da-vinci.css",
    wallpaper: wallpapers.themes.find((w) => w.id === "leonardoDaVinci").src,
    soundScheme: "Leonardo da Vinci",
    iconScheme: "leonardo-da-vinci",
  },
  "more-windows": {
    id: "more-windows",
    name: "More Windows",
    stylesheet: "more-windows.css",
    wallpaper: wallpapers.themes.find((w) => w.id === "moreWindows").src,
    soundScheme: "Default", // Or create a new sound scheme if one exists
    iconScheme: "more-windows",
  },
  mystery: {
    id: "mystery",
    name: "Mystery",
    stylesheet: "mystery.css",
    wallpaper: wallpapers.themes.find((w) => w.id === "mystery").src,
    soundScheme: "Mystery",
    iconScheme: "mystery",
  },
  nature: {
    id: "nature",
    name: "Nature",
    stylesheet: "nature.css",
    wallpaper: wallpapers.themes.find((w) => w.id === "nature").src,
    soundScheme: "Nature",
    iconScheme: "nature",
  },
  science: {
    id: "science",
    name: "Science",
    stylesheet: "science.css",
    wallpaper: wallpapers.themes.find((w) => w.id === "science").src,
    soundScheme: "Science",
    iconScheme: "science",
  },
  "the-golden-era": {
    id: "the-golden-era",
    name: "The Golden Era",
    stylesheet: "the-golden-era.css",
    wallpaper: wallpapers.themes.find((w) => w.id === "theGoldenEra").src,
    soundScheme: "The Golden Era",
    iconScheme: "the-golden-era",
  },
  travel: {
    id: "travel",
    name: "Travel",
    stylesheet: "travel.css",
    wallpaper: wallpapers.themes.find((w) => w.id === "travel").src,
    soundScheme: "Travel",
    iconScheme: "travel",
  },
  "windows-98": {
    id: "windows-98",
    name: "Windows 98",
    stylesheet: "win-98.css",
    wallpaper: wallpapers.themes.find((w) => w.id === "windows98").src,
    soundScheme: "Windows 98",
    iconScheme: "windows-98",
  },
};
